CREATE USER readonly_x WITH LOGIN PASSWORD 'pass_x' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION VALID UNTIL 'infinity';
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_x;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_x;
